version: "3.9"

services:
    jira
:
        container_name: php
        image: atlassian/jira-software:8.20
        restart: always
        build:
            context: .
            dockerfile: Dockerfile
            target: base
        ports:
            - 8080:80
